### ISSUE TITLE
PCJ fail to compile against the latest libpmemobj

### ISSUE THREAD

**Issue by krzycz** [pmem/issues#598]
```
$ cd ../pcj
$ make
...
g++ -O3 -DNDEBUG -fPIC -I/usr/lib/jvm/java-openjdk//include -I/usr/lib/jvm/java-openjdk//include/linux -o target/cppbuild/hashmap_tx.o -c src/main/cpp/hashmap_tx.cpp
In file included from /usr/include/string.h:32:0,
                 from /usr/local/include/libpmemobj/tx.h:41,
                 from /usr/local/include/libpmemobj.h:52,
                 from src/main/cpp/hashmap_tx.cpp:29:
src/main/cpp/hashmap_tx.cpp: In function ‘NEPMEMoid hm_tx_insert(PMEMobjpool*, hashmap_tx_toid, uint64_t, uint64_t)’:
src/main/cpp/hashmap_tx.cpp:163:51: error: the value of ‘h’ is not usable in a constant expression
       TX_ADD_FIELD(D_RO(hashmap)->buckets, bucket[h]);
                                                   ^
src/main/cpp/hashmap_tx.cpp:145:11: note: ‘uint64_t h’ is not const
  uint64_t h = hash(&hashmap, &buckets, key);
           ^
In file included from /usr/include/string.h:32:0,
                 from /usr/local/include/libpmemobj/tx.h:41,
                 from /usr/local/include/libpmemobj.h:52,
                 from src/main/cpp/hashmap_tx.cpp:29:
src/main/cpp/hashmap_tx.cpp: In function ‘NEPMEMoid hm_tx_remove(PMEMobjpool*, hashmap_tx_toid, uint64_t)’:
src/main/cpp/hashmap_tx.cpp:217:48: error: the value of ‘h’ is not usable in a constant expression
    TX_ADD_FIELD(D_RO(hashmap)->buckets, bucket[h]);
                                                ^
src/main/cpp/hashmap_tx.cpp:204:11: note: ‘uint64_t h’ is not const
  uint64_t h = hash(&hashmap, &buckets, key);
           ^
Makefile:101: recipe for target 'target/cppbuild/hashmap_tx.o' failed
make: *** [target/cppbuild/hashmap_tx.o] Error 1
```

Caused by https://github.com/pmem/nvml/pull/1785
