### ISSUE TITLE
common: pmdk doesn't compile with ndctl installed with versions 58.3 and 58.4

### ISSUE THREAD

**Issue by llugin** [pmem/issues#765]
Libndctl version check before pmdk compilation is bypassed for these ndctl versions.

```
$ cd ndctl
$ git checkout v58.3 # or v58.4
[...]
```

Error output:

> ../../src/../src/common/os_dimm_ndctl.c: In function ‘os_dimm_usc’:
../../src/../src/common/os_dimm_ndctl.c:208:11: error: implicit declaration of function ‘ndctl_cmd_smart_get_shutdown_count’; did you mean ‘ndctl_cmd_smart_get_shutdown_state’? [-Werror=implicit-function-declaration]
  *usc += ndctl_cmd_smart_get_shutdown_count(cmd);
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          ndctl_cmd_smart_get_shutdown_state
../../src/../src/common/os_dimm_ndctl.c:208:8: error: conversion to ‘uint64_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
  *usc += ndctl_cmd_smart_get_shutdown_count(cmd);
       ^~

Found on: 1.3+b2-653-gf987b264f

**Comment by llugin** [comment]
verified on 1.4-rc3-26-gcf1ca81a8
