### ISSUE TITLE
Error during build on Ubuntu 15.04 with gcc 4.9.2

### ISSUE THREAD

**Issue by michalsnochowski** [pmem/issues#51]
An error occurred when building on Ubuntu 15.04 with gcc 4.9.2:

In file included from ut_file.c:37:0:
unittest.h:447:39: error: 'struct sigvec' declared inside parameter list [-Werror]
   int sig, struct sigvec *vec, struct sigvec *ovec);
                                       ^
unittest.h:447:39: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
In file included from ut.c:42:0:
unittest.h:447:39: error: 'struct sigvec' declared inside parameter list [-Werror]
   int sig, struct sigvec *vec, struct sigvec *ovec);
                                       ^
unittest.h:447:39: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
In file included from ut_pthread.c:37:0:
unittest.h:447:39: error: 'struct sigvec' declared inside parameter list [-Werror]
   int sig, struct sigvec *vec, struct sigvec *ovec);
                                       ^
unittest.h:447:39: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
In file included from ut_alloc.c:37:0:
unittest.h:447:39: error: 'struct sigvec' declared inside parameter list [-Werror]
   int sig, struct sigvec *vec, struct sigvec *ovec);
                                       ^
unittest.h:447:39: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
In file included from ut_signal.c:37:0:
unittest.h:447:39: error: 'struct sigvec' declared inside parameter list [-Werror]
   int sig, struct sigvec *vec, struct sigvec *ovec);
                                       ^
unittest.h:447:39: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
ut_signal.c:44:39: error: 'struct sigvec' declared inside parameter list [-Werror]
   int sig, struct sigvec *vec, struct sigvec *ovec)
                                       ^
ut_signal.c:43:1: error: conflicting types for 'struct sigvec'
 ut_sigvec(const char *file, int line, const char *func,
 ^
In file included from ut_signal.c:37:0:
unittest.h:446:5: note: previous declaration of 'struct sigvec' was here
 int ut_sigvec(const char *file, int line, const char *func,
     ^
ut_signal.c: In function 'struct sigvec':
ut_signal.c:46:2: error: implicit declaration of function 'struct sigvec' [-Werror=implicit-function-declaration]
  int retval = sigvec(sig, vec, ovec);
  ^

**Comment by michalsnochowski** [comment]
Verified on 0.1+b16-48-ge205184
