### ISSUE TITLE
PMDK does not compile with clang-5.0

### ISSUE THREAD

**Issue by mrharrylp** [pmem/issues#783]
New Fedora 27 comes with clang-5.0 and failed building

Found on commit: 22ab13e6242dd6b536c37bc47f07de2e61293392

error in [test log](http://10.91.123.57:8080/blue/organizations/jenkins/pmdk_cpp_tests/detail/pmdk_cpp_tests/46/pipeline):
```
obj_cpp_ptr.cpp:337:38: error: lambda capture 'pop' is not used [-Werror,-Wunused-lambda-capture]
                nvobj::transaction::exec_tx(pop, [&pop] {
                                                   ^
```

**Comment by gaweinbergi** [comment]
Verified on FreeBSD 11.1 with clang 5.0.

**Comment by mrharrylp** [comment]
to be sure, I also verified current master branch on Fedora 27 - works fine, thanks
